Doc: misc '-h' output

diff --git a/daiker b/daiker
--- a/daiker
+++ b/daiker
@@ -2,17 +2,50 @@
 # https://github.com/daimh/daiker
 set -fEeuo pipefail
 trap "exit 1" TERM
+
 function die {
-	if [ "$1" != help ]
+	# 20260328
+	if [ "$#" -eq 2 ]
 	then
-		echo -e "$1" | tr "	" " " | tr -s " " 1>&2
-	else
-		grep "#@" /proc/$$/fd/255 \
-			| grep -e "#@@$2" -e "#@ " -e "#@	" \
-			| sed "s/#@@$2/#@/" \
+		grep -e "#@@$2" -e "#@ " -e "#@	" -e "#@$" /proc/$$/fd/255 \
 			| sed -n '/^#@ HELP_START/,/^#@ HELP_END/p' \
 			| grep -v "^#@ HELP_" \
-			| sed "s/#@//; s/ \+/ /; s/\t\+/\t/; s/^ //"
+			| sed "
+				s/^#@@$2//;
+				s/^#@//;
+				s/) #@$//;
+				s/) #@ =/=/;
+				s/) #@ /\n\t\t/;
+				s/\t#@ /\t/;
+				s/^\t\t/\t/;
+				s/^ //" \
+			| sed "
+				s/\t/    /g;
+				s/ | /, /"
+	elif [ "$#" -eq 1 ]
+	then
+		printf "$1\n"
+	else
+		printf "daiker — A Docker-like VM tool based on QEMU
+
+USAGE
+    daiker <command> [OPTIONS] [ARGS]
+
+COMMANDS
+    build
+        Build a base image (similar to a Docker image)
+
+    run
+        Create and run an overlay image based on a base image
+        (similar to a Docker container)
+
+    convert
+        Convert an overlay image into a base image
+
+OPTIONS
+    -h, --help
+        Show help information
+"
 	fi
 	Pgid=$(ps -o pgid= $$ | tr -d " ")
 	[ $(cat /proc/$Pgid/task/$Pgid/children | wc -w) -lt 2 ] \
@@ -25,7 +58,7 @@ function get_free_ports {
 	export LC_ALL=C
 	sleep 0.$(($RANDOM%10))
 	join -v 1 <(seq $2 $3) \
-		<(ss -4ln${1:0:1} | tail -n +2 | awk '{print $4}' | cut -d : -f 2 |sort) \
+		<(ss -4ln${1:0:1} |tail -n +2 |awk '{print $4}' |cut -d : -f 2 |sort) \
 		| shuf | head -n $4
 }
 
@@ -40,29 +73,21 @@ function get_hostfwd {
 			printf "hostfwd=%s::%s-:%s", Proto, $1, $2}'
 }
 
-function usage {
-	die "Usage: daiker <command> [-h] [<args>]
-commands:
-	build
-	run	
-	convert"
-}
-
 function is_not_base_image {
 	qemu-img info $1 | grep -q "backing file:"
 }
 
 function version {
-	die 20260319
+	die 20260328
 }
 
-[ $# -gt 0 ] || usage
-[ "$1" != "-h" -a "$1" != "--help" -a "$1" != "help" ] || usage
+[ $# -gt 0 ] || die
+[ "$1" != "-h" -a "$1" != "--help" -a "$1" != "help" ] || die
 Command=$1
 OptShort="hvc:r:i:de:M:T:U:D:Q:"
 OptLong="help,version,cpu:,ram:,iso:,disable-public-net,enable-private-net:\
 	,mount:,tcp-ports:,udp-ports:display:,qemu-parameters"
-shift || usage
+shift || die
 if [ "$Command" = "build" ]
 then
 	OptShort="${OptShort}H:"
@@ -107,47 +132,72 @@ do
 #@@build	daiker build - build a base image
 #@@run	daiker run - run an overlay image
 #@@convert	daiker convert - convert an overlay image to a base image
-#@@ SYNOPSIS
+#@ SYNOPSIS
 #@@build	daiker build [OPTION]... [FILE]
 #@@run	daiker run [OPTION]... [FILE]
 #@@convert	daiker convert [FILE]
 #@ EXAMPLE
-#@@build	daiker build -H 50 -i ubuntu-18.04.5-live-server-amd64.iso BionicBeaverBase.qcow2
+#@@build	daiker build -H 50 -i ubuntu-18.04.5-live-server-amd64.iso \
+#@@build	    BionicBeaverBase.qcow2
 #@@run	daiker run -b BionicBeaverBase.qcow2 BionicBeaverTest.qcow2
 #@@run	daiker run -T 22 -T 80 BionicBeaverTest.qcow2
-#@@run	wget https://dl-cdn.alpinelinux.org/alpine/edge/releases/x86_64/netboot/vmlinuz-virt
-#@@run	wget https://dl-cdn.alpinelinux.org/alpine/edge/releases/x86_64/netboot/initramfs-virt
-#@@run	daiker run -Q '-kernel vmlinuz-virt' -Q '-initrd initramfs-virt' -Q '-append alpine_repo=https://dl-cdn.alpinelinux.org/alpine/v3.16/main[TAB]modloop=https://dl-cdn.alpinelinux.org/alpine/edge/releases/x86_64/netboot/modloop-virt' /dev/null # Please replace [TAB] with TAB
+#@@run	wget https://dl-cdn.alpinelinux.org/alpine/edge/releases/x86_64/netboot\
+#@@run	    /vmlinuz-virt
+#@@run	wget https://dl-cdn.alpinelinux.org/alpine/edge/releases/x86_64/netboot\
+#@@run	    /initramfs-virt
+#@@run	daiker run -Q '-kernel vmlinuz-virt' -Q '-initrd initramfs-virt' -Q \
+#@@run	    '-append alpine_repo=https://dl-cdn.alpinelinux.org/alpine/v3.16\
+#@@run	    /main[TAB]modloop=https://dl-cdn.alpinelinux.org/alpine/edge\
+#@@run	    /releases/x86_64/netboot/modloop-virt' /dev/null
+#@@run	    # Please replace [TAB] with TAB
 #@@convert	daiker convert BionicBeaverTest.qcow2
 #@ OPTIONS
-		-h | --help)	#@ print help information
+		-h | --help) #@
+			#@ Display help information
 			die help $Command;;
-		--version)	#@ print version
+		--version) #@
+			#@ Display version information
 			version ;;
-		-v )	#@ verbose output
+		-v ) #@
+			#@ Enable verbose output
 			set -x
 			shift ;;
-		-c | --cpu)	#@ =Cpu, number of cpus, default 2
-			[ "$2" -eq "$2" ] 2> /dev/null || die "ERR-021: invalid number: -c $2"
+		-c | --cpu) #@ =CPU
+			#@ Number of CPUs (default: 2)
+			[ "$2" -eq "$2" ] 2> /dev/null \
+				|| die "ERR-021: invalid number: -c $2"
 			Cpu=$2
 			shift 2 ;;
-		-r | --ramsize)	#@ =RamSize, memory size, in GB, default 4
-			[ "$2" -eq "$2" ] 2> /dev/null || die "ERR-022: invalid number: -r $2"
+		-r | --ramsize) #@ =RAMSIZE
+			#@ Memory size in GB (default: 4)
+			[ "$2" -eq "$2" ] 2> /dev/null \
+				|| die "ERR-022: invalid number: -r $2"
 			RamSize=$2
 			shift 2 ;;
-		-i | --iso)	#@ =Iso file, used as cdrom
+		-i | --iso) #@ =FILE
+			#@ ISO file to use as as the CD-ROM
 			Iso=$2
 			shift 2 ;;
-		-d | --disable-public-net)	#@ disable public net. The machine won't be able to access the Internet
+		-d | --disable-public-net) #@
+			#@ Disable public networking. The VM will not have Internet access.
 			DisablePublicNet=YES
 			shift 1 ;;
-		-e | --enable-private-net)	#@ =random/11:22:33, add a NIC with a specfic or random mac address to share the same private network traffic with other virtual machines that also used '-e'. The mac address will be prepended with '52:54:00'
+		-e | --enable-private-net) #@ =random|11:22:33
+			#@ Add a NIC with a specfic or random MAC address to share a private
+			#@ network with other VMs using this option. The MAC address will be
+			#@ prefixed with '52:54:00'.
 			EnablePrivateNets+=($2)
 			shift 2 ;;
-		-M | --mount)	#@ =DIR, allows virtual machine to mount multiple directories on the physical host with some command like 'mount -t 9p -o msize=1048576 daiker-0 /mnt', where 'daiker-0' means the first -m option. Default CentOS or Windows doesn't support this feature
+		-M | --mount) #@ =DIR
+			#@ Mount one or more host directories inside the VM. Example:
+			#@     mount -t 9p -o msize=1048576 daiker-0 /mnt
+			#@ where 'daiker-0' refers to the first -M option.
+			#@ Note: Default CentOS and Windows images may not support this
+			#@ feature.
 			MountDirs+=($2)
 			shift 2 ;;
-		-T | --tcp-ports)	#@ =VMPORT or VMPORT-HOSTPORT, tcp port HOSTPORT on the host is forwarded to VMPORT on the virtual machine
+		-T | --tcp-ports) #@ =VMPORT| VMPORT-HOSTPORT
+			#@ Forward TCP port HOSTPORT on the host to VMPORT on the VM
 			if [[ "$2" == *"-"* ]]
 			then
 				IFS=- read VPORT HPORT <<< "$2"
@@ -161,7 +211,8 @@ do
 				TcpPorts+=($2)
 			fi
 			shift 2 ;;
-		-U | --udp-ports)	#@ =VMPORT or VMPORT-HOSTPORT, udp port HOSTPORT on the host is forwarded to VMPORT on the virtual machine
+		-U | --udp-ports) #@ =VMPORT| VMPORT-HOSTPORT
+			#@ Forward UDP port HOSTPORT on the host to VMPORT on the VM
 			if [[ "$2" == *"-"* ]]
 			then
 				IFS=- read VPORT HPORT <<< "$2"
@@ -175,19 +226,30 @@ do
 				UdpPorts+=($2)
 			fi
 			shift 2 ;;
-		-D | --display)	#@ gtk/vnc/[VncDisplayNum]/none/nographic/, default gtk, which requires X
+		-D | --display) #@ =gtk|vnc|[VncDisplayNum]|none|nographic
+			#@ Default: gtk (requires X server)
 			QemuDisplay=$2
 			shift 2 ;;
-		-Q | --qemu-parameters)	#@ Other qemu parameters, can be used multiple times. For example, to use a usb device, run "sudo chown $USER /dev/bus/usb/003/006; daiker run -Q "-device usb-ehci,id=ehci -device usb-host,hostbus=3,hostaddr=6" test.qcow2
+		-Q | --qemu-parameters) #@ =QEMUPARAMS
+			#@ Additional QEMU parameters (can be used multiple times).
+			#@ Exampel:
+			#@     sudo chown $USER /dev/bus/usb/003/006
+			#@     daiker run -Q "-device usb-ehci,id=ehci \
+			#@         -device usb-host,hostbus=3,hostaddr=6" test.qcow2
 			QemuParameters+=("$2")
 			shift 2 ;;
-		-b | --base)	#@ =Base, the base image that a new virtual machine will be created from. Base should be the output file of 'daiker build'. Its actual format is a qemu image without backing file
+		-b | --base) #@ =BASE
+			#@ Base image used to create a new VM. Must be the output of
+			#@ 'daiker build' (a QEMU image without a backing file)
 			Base=$2
 			shift 2 ;;
-		-F | --force)	#@ force to run on either a base image to modify it, or an overlay image as base. It could corrupt other overlay images depending on the image being modified. Use at your risk!
+		-F | --force) #@
+			#@ Force operation on a base image. It corrupts backing
+			#@ image.  Use at your risk!!!
 			Force=YES
 			shift ;;
-		-H | --hda-size)	#@ =SIZE, hard drive size, in GB, default 50
+		-H | --hda-size) #@ =SIZE
+			#@ Disk size in GB (default: 50)
 			[ "$2" -eq "$2" ] 2> /dev/null \
 				|| die "ERR-025: invalid number: -H $2"
 			HdSize=$2
@@ -200,7 +262,7 @@ do
 #@ AUTHOR
 #@	Manhong Dai
 #@ COPYRIGHT 
-#@	© University of Michigan 2002-2025
+#@	© University of Michigan 2002-2026
 #@ LICENSE
 #@	MIT
 #@ HELP_END
@@ -345,7 +407,7 @@ then
 				use -F at your own risk!"
 	fi
 else
-	usage
+	die
 fi
 QemuBin=$(command -v qemu-system-x86_64 2>/dev/null) \
 	|| QemuBin="$(command -v qemu-kvm 2>/dev/null)" \
